/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{tenantId}/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trigger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReports"];
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["narrative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["explain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tenants"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sample-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loadSampleData"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/{connectorId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/{connectorId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connectors/{connectorId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/business-units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBusinessUnit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["html"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["trends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/in-flight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inFlight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/friction/teams/{teamId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["evidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/friction/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["connectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/{connectorId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["structure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connector-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateAiPolicyRequest: {
            enabled: boolean;
            provider: string;
            baseUrl: string;
            model: string;
            secret: string;
            /** Format: double */
            temperature: number;
            /** Format: int32 */
            maxTokens: number;
        };
        AiPolicyView: {
            enabled: boolean;
            provider: string;
            baseUrl: string;
            model: string;
            hasSecret: boolean;
            /** Format: double */
            temperature: number;
            /** Format: int32 */
            maxTokens: number;
        };
        GenerateReportRequest: {
            type: string;
            /** Format: int32 */
            weeks?: number;
        };
        ReportView: {
            /** Format: uuid */
            id: string;
            type: string;
            title: string;
            status: string;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            /** Format: int32 */
            weeks: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: string;
        };
        ExplanationView: {
            narrative: string;
            provider: string;
            model: string;
            citedNumbers: string[];
            /** Format: date-time */
            generatedAt: string;
            disclaimer: string;
        };
        ExplainRequest: {
            /** Format: int32 */
            weeks: number;
        };
        CreateTenantRequest: {
            name: string;
            slug: string;
        };
        TenantView: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        CreateTeamRequest: {
            /** Format: uuid */
            businessUnitId: string;
            name: string;
        };
        IngestionResult: {
            /** Format: int32 */
            emitted: number;
            /** Format: int32 */
            inserted: number;
            /** Format: int32 */
            updated: number;
            /** Format: int32 */
            unchanged: number;
        };
        PipelineResult: {
            ingestion: components["schemas"]["IngestionResult"];
            /** Format: int32 */
            teamsComputed: number;
            /** Format: int32 */
            itemsCorrelated: number;
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        RegisterConnectorRequest: {
            type: string;
            name: string;
            config?: {
                [key: string]: string;
            };
            secret?: string;
        };
        ConnectorAdminView: {
            /** Format: uuid */
            id: string;
            type: string;
            name: string;
            status: string;
            simulation: boolean;
            config: {
                [key: string]: string;
            };
            hasSecret: boolean;
        };
        TestConnectionResult: {
            outcome: string;
            message: string;
        };
        SetStatusRequest: {
            status: string;
        };
        CreateBusinessUnitRequest: {
            /** Format: uuid */
            organizationId: string;
            name: string;
        };
        SessionView: {
            /** Format: uuid */
            tenantId: string;
            organizationName: string;
        };
        AuthConfigView: {
            mode: string;
            issuer: string;
            clientId: string;
        };
        ReportPageView: {
            items: components["schemas"]["ReportView"][];
            nextCursor: string;
            hasMore: boolean;
        };
        RecommendationView: {
            code: string;
            severity: string;
            title: string;
            rationale: string;
            actions: string[];
            metricRefs: string[];
        };
        ReportDocument: {
            /** Format: int32 */
            reportVersion: number;
            title: string;
            /** Format: date-time */
            periodStart: string;
            /** Format: date-time */
            periodEnd: string;
            /** Format: int32 */
            weeks: number;
            /** Format: date-time */
            generatedAt: string;
            metricVersion: string;
            totals: components["schemas"]["ReportTotals"];
            teams: components["schemas"]["ReportTeamSection"][];
        };
        ReportDocumentView: {
            report: components["schemas"]["ReportView"];
            document: components["schemas"]["ReportDocument"];
        };
        ReportTeamSection: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            /** Format: int32 */
            frictionScore: number;
            dominantCause: string;
            points: components["schemas"]["TrendPointView"][];
            recommendations: components["schemas"]["RecommendationView"][];
            /** Format: int32 */
            inFlightCount: number;
            /** Format: int32 */
            blockedInFlightCount: number;
        };
        ReportTotals: {
            /** Format: int32 */
            teamsReporting: number;
            /** Format: int32 */
            itemsResolved: number;
            /** Format: int64 */
            avgCycleSec: number;
            /** Format: int64 */
            p85CycleSec: number;
            /** Format: int32 */
            flowEfficiencyPct: number;
            /** Format: int32 */
            blockedPct: number;
            /** Format: int32 */
            reviewWaitPct: number;
            /** Format: int32 */
            avgFrictionScore: number;
        };
        TrendPointView: {
            weekStart: string;
            /** Format: int32 */
            itemsResolved: number;
            /** Format: int64 */
            avgCycleSec: number;
            /** Format: int64 */
            p85CycleSec: number;
            /** Format: int32 */
            flowEfficiencyPct: number;
            /** Format: int32 */
            blockedPct: number;
            /** Format: int32 */
            reviewWaitPct: number;
            /** Format: int32 */
            frictionScore: number;
        };
        TeamTrendView: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            points: components["schemas"]["TrendPointView"][];
        };
        TrendsView: {
            /** Format: int32 */
            rangeWeeks: number;
            teams: components["schemas"]["TeamTrendView"][];
        };
        InFlightItemView: {
            workItemKey: string;
            title: string;
            state: string;
            /** Format: int64 */
            ageSec: number;
            blocked: boolean;
        };
        TeamInFlightView: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            items: components["schemas"]["InFlightItemView"][];
        };
        TeamRecommendationsView: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            /** Format: int32 */
            frictionScore: number;
            recommendations: components["schemas"]["RecommendationView"][];
        };
        FrictionEvidenceView: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            metricVersion: string;
            items: components["schemas"]["WorkItemEvidenceView"][];
        };
        TransitionEvidenceView: {
            /** Format: int32 */
            seq: number;
            fromState: string;
            toState: string;
            /** Format: int64 */
            atEpochSec: number;
        };
        WorkItemEvidenceView: {
            workItemKey: string;
            title: string;
            type: string;
            status: string;
            /** Format: int64 */
            cycleTimeSec: number;
            /** Format: int64 */
            activeSec: number;
            /** Format: int64 */
            blockedSec: number;
            /** Format: int64 */
            reviewWaitSec: number;
            /** Format: int64 */
            waitingSec: number;
            /** Format: int32 */
            reworkCount: number;
            pullRequestKey: string;
            buildKey: string;
            buildStatus: string;
            qualityGateKey: string;
            qualityGateStatus: string;
            transitions: components["schemas"]["TransitionEvidenceView"][];
        };
        FrictionMetricView: {
            key: string;
            name: string;
            purpose: string;
            formula: string;
            inputs: components["schemas"]["JsonNode"];
            grain: string;
            caveats: string;
            gamingRisks: string;
        };
        FrictionSummaryView: {
            metric: components["schemas"]["FrictionMetricView"];
            metricVersion: string;
            computedAt: string;
            simulation: boolean;
            teams: components["schemas"]["TeamFrictionView"][];
            /** Format: int32 */
            teamsReporting: number;
        };
        JsonNode: Record<string, unknown>;
        TeamFrictionView: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            /** Format: int32 */
            frictionScore: number;
            dominantCause: string;
            /** Format: int32 */
            workItems: number;
            /** Format: int64 */
            totalCycleSec: number;
            /** Format: int64 */
            activeSec: number;
            /** Format: int64 */
            waitingSec: number;
            /** Format: int64 */
            blockedSec: number;
            /** Format: int64 */
            reviewWaitSec: number;
            /** Format: int32 */
            reworkCount: number;
            /** Format: int32 */
            flowEfficiencyPct: number;
            /** Format: int32 */
            blockedPct: number;
            /** Format: int32 */
            reviewWaitPct: number;
        };
        ConnectorView: {
            /** Format: uuid */
            id: string;
            type: string;
            name: string;
            status: string;
            simulation: boolean;
        };
        PageViewConnectorView: {
            items: components["schemas"]["ConnectorView"][];
            nextCursor: string;
            hasMore: boolean;
        };
        AiStatusResponse: {
            enabled: boolean;
        };
        BusinessUnitView: {
            /** Format: uuid */
            id: string;
            name: string;
            teams: components["schemas"]["TeamView"][];
        };
        OrganizationView: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            businessUnits: components["schemas"]["BusinessUnitView"][];
        };
        TeamView: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        ConnectorTypeView: {
            type: string;
            displayName: string;
            description: string;
            configSchema: string;
            secretLabel: string;
            syncAvailable: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiPolicyView"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAiPolicyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiPolicyView"];
                };
            };
        };
    };
    trigger: {
        parameters: {
            query?: never;
            header?: {
                "X-EIP-Webhook-Token"?: string;
            };
            path: {
                tenantId: string;
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, unknown>;
                };
            };
        };
    };
    listReports: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportPageView"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateReportRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportView"];
                };
            };
        };
    };
    narrative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExplanationView"];
                };
            };
        };
    };
    explain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExplanationView"];
                };
            };
        };
    };
    tenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TenantView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TenantView"];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    loadSampleData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PipelineResult"];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConnectorAdminView"][];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConnectorRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConnectorAdminView"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TestConnectionResult"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PipelineResult"];
                };
            };
        };
    };
    setStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConnectorAdminView"];
                };
            };
        };
    };
    createBusinessUnit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusinessUnitRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionView"];
                };
            };
        };
    };
    authConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthConfigView"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportDocumentView"];
                };
            };
        };
    };
    html: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    trends: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrendsView"];
                };
            };
        };
    };
    inFlight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamInFlightView"][];
                };
            };
        };
    };
    recommendations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamRecommendationsView"][];
                };
            };
        };
    };
    evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FrictionEvidenceView"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FrictionSummaryView"];
                };
            };
        };
    };
    connectors: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageViewConnectorView"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TestConnectionResult"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiStatusResponse"];
                };
            };
        };
    };
    structure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizationView"][];
                };
            };
        };
    };
    types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConnectorTypeView"][];
                };
            };
        };
    };
}
