// Thin re-export layer over `./generated.ts` (openapi-typescript output, generated from the
// committed `backend/eip-app/openapi/eip-openapi-v1.json` via `pnpm generate:api` — see
// package.json / CI's `generate:api:check` gate). NEVER hand-edit `generated.ts`; if the backend
// contract changes, run `pnpm generate:api` and re-run tests. Every interface below is asserted to
// carry the SAME field set and names the hand-written types previously declared (verified
// field-for-field against this snapshot's `components.schemas`), so no import path anywhere in the
// codebase needed to change — only this file's internals moved from hand-written to generated-backed.
//
// The committed OpenAPI snapshot is generated by springdoc from Java records/POJOs with no
// bean-validation annotations on response fields, so — for every response (non-request) schema —
// it omits BOTH of the following, which we recover from the backend's actual serialization
// semantics (documented per-field below) rather than inventing it:
//   - `required`: springdoc emits NO `required` array on any response DTO, which — read literally —
//     would make openapi-typescript treat every field as optional. That is wrong for the vast
//     majority of fields (Jackson's default is ALWAYS-inclusion — the key is always present), so
//     codegen runs with `--properties-required-by-default` (required unless proven otherwise) and
//     the genuinely conditional fields (`@JsonInclude(Include.NON_NULL)` — omitted from the JSON
//     entirely when null, arriving as `undefined`) are individually widened back to optional via an
//     `Omit<...> & {...}` override, sourced from the same field-by-field audit the original
//     hand-written file recorded.
//   - `enum`: springdoc does not emit `enum`/`x-enum` for these fields (verified: zero `"enum"` or
//     `"nullable"` keys anywhere in the committed snapshot), so a handful of fields the backend
//     actually returns as a closed literal set come through generated as plain `string`. Those are
//     individually narrowed back to their literal union via the same override pattern — never
//     silently widened to `string` (would defeat exhaustiveness checks / typo-safety at call sites).
// `--empty-objects-unknown` makes the one genuinely-arbitrary-JSON schema (`JsonNode`, `{type:
// object}` with no properties) generate as `Record<string, unknown>` instead of the uninhabited
// `Record<string, never>` (which would make every property access a type error).
//
// Two nullability idioms, unchanged from the original hand-written analysis (DEBT-020 item 5):
//   - `@Nullable`, Jackson's default ALWAYS inclusion (e.g. SessionView.organizationName,
//     AuthConfigView.issuer/clientId, AiPolicyView.provider/baseUrl/model,
//     ConnectorTypeView.secretLabel, ReportView.completedAt): a real JSON `null` is always sent —
//     typed `T | null` here; `=== null`/`!== null` checks against them are correct.
//   - `@Nullable` + `@JsonInclude(Include.NON_NULL)` (PageView's nextCursor, FrictionSummaryView's
//     metric/metricVersion/computedAt, FrictionEvidenceView's teamName, WorkItemEvidenceView's
//     workItemKey/pullRequestKey/buildKey/buildStatus/qualityGateKey/qualityGateStatus,
//     TransitionEvidenceView's fromState): the field is OMITTED entirely when null, so it arrives as
//     `undefined` — typed as an optional property (`field?: T`), never `T | null`.

import type { components } from './generated';

export type SessionView = Omit<components['schemas']['SessionView'], 'organizationName'> & {
  organizationName: string | null;
};

// ── M5 OIDC login (Wave S1b) ────────────────────────────────────────────────────────────────────

/**
 * GET /api/v1/session/auth — no auth, no tenant header. Tells the SPA how to authenticate: HEADER
 * (today's dev tenant header, zero-auth) or OIDC (Authorization Code + PKCE against `issuer`).
 *
 * `mode` is a closed Java enum but springdoc emits it as plain `string` (no `enum` in the
 * snapshot) — narrowed back to the literal union here.
 */
export type AuthConfigView = Omit<
  components['schemas']['AuthConfigView'],
  'mode' | 'issuer' | 'clientId'
> & {
  mode: 'HEADER' | 'OIDC';
  issuer: string | null;
  clientId: string | null;
};

export type ConnectorView = components['schemas']['ConnectorView'];

export type PageViewConnectorView = Omit<
  components['schemas']['PageViewConnectorView'],
  'nextCursor'
> & {
  nextCursor?: string;
};

export type TeamFrictionView = components['schemas']['TeamFrictionView'];

/** `inputs` (contract: `JsonNode`) generates as `Record<string, unknown>` — an arbitrary JSON object. */
export type FrictionMetricView = components['schemas']['FrictionMetricView'];

export type TransitionEvidenceView = Omit<
  components['schemas']['TransitionEvidenceView'],
  'fromState'
> & {
  fromState?: string;
};

export type WorkItemEvidenceView = Omit<
  components['schemas']['WorkItemEvidenceView'],
  | 'workItemKey'
  | 'pullRequestKey'
  | 'buildKey'
  | 'buildStatus'
  | 'qualityGateKey'
  | 'qualityGateStatus'
  | 'transitions'
> & {
  workItemKey?: string;
  pullRequestKey?: string;
  buildKey?: string;
  buildStatus?: string;
  qualityGateKey?: string;
  qualityGateStatus?: string;
  /** Cascaded override — TransitionEvidenceView's own `fromState` optionality must flow through. */
  transitions: TransitionEvidenceView[];
};

export type FrictionEvidenceView = Omit<
  components['schemas']['FrictionEvidenceView'],
  'teamName' | 'items'
> & {
  teamName?: string;
  /** Cascaded override — WorkItemEvidenceView's field-level overrides must flow through. */
  items: WorkItemEvidenceView[];
};

export type FrictionSummaryView = Omit<
  components['schemas']['FrictionSummaryView'],
  'metric' | 'metricVersion' | 'computedAt'
> & {
  metric?: FrictionMetricView;
  metricVersion?: string;
  computedAt?: string;
};

// ── M1 admin panel (ADR-022) ────────────────────────────────────────────────────────────────────

export type TenantView = components['schemas']['TenantView'];

/** No `TeamAdminView` component exists in the contract — springdoc names this schema `TeamView`. */
export type TeamAdminView = components['schemas']['TeamView'];

export type BusinessUnitView = components['schemas']['BusinessUnitView'];

export type OrganizationView = components['schemas']['OrganizationView'];

export type ConnectorTypeView = Omit<components['schemas']['ConnectorTypeView'], 'secretLabel'> & {
  secretLabel: string | null;
};

export type ConnectorAdminView = components['schemas']['ConnectorAdminView'];

/**
 * `outcome` is a closed Java enum but springdoc emits it as plain `string` — narrowed back to the
 * literal union here.
 */
export type TestConnectionResult = Omit<
  components['schemas']['TestConnectionResult'],
  'outcome'
> & {
  outcome: 'OK' | 'NOT_AVAILABLE' | 'FAILED';
};

/** No `SampleDataResult` component exists in the contract — springdoc names this schema `PipelineResult`. */
export type SampleDataResult = components['schemas']['PipelineResult'];

// ── M3 dashboard: trends, in-flight, recommendations (TASK-0020) ──────────────────────────────────

export type TrendPointView = components['schemas']['TrendPointView'];

export type TeamTrendView = components['schemas']['TeamTrendView'];

export type TrendsView = components['schemas']['TrendsView'];

export type InFlightItemView = components['schemas']['InFlightItemView'];

export type TeamInFlightView = components['schemas']['TeamInFlightView'];

/**
 * `severity` is a closed Java enum but springdoc emits it as plain `string` — narrowed back to the
 * literal union here.
 */
export type RecommendationView = Omit<components['schemas']['RecommendationView'], 'severity'> & {
  severity: 'INFO' | 'WARN' | 'CRITICAL';
};

export type TeamRecommendationsView = Omit<
  components['schemas']['TeamRecommendationsView'],
  'recommendations'
> & {
  /** Cascaded override — RecommendationView's `severity` literal-union override must flow through. */
  recommendations: RecommendationView[];
};

// ── M4 deterministic reports (TASK-0022) ───────────────────────────────────────────────────────

export type ReportView = Omit<components['schemas']['ReportView'], 'completedAt'> & {
  completedAt: string | null;
};

/** No `PageViewReportView` component exists in the contract — springdoc names this schema `ReportPageView`. */
export type PageViewReportView = Omit<
  components['schemas']['ReportPageView'],
  'nextCursor' | 'items'
> & {
  nextCursor?: string;
  /** Cascaded override — ReportView's `completedAt` nullability override must flow through. */
  items: ReportView[];
};

export type ReportTotals = components['schemas']['ReportTotals'];

export type ReportTeamSection = Omit<
  components['schemas']['ReportTeamSection'],
  'recommendations'
> & {
  /** Cascaded override — RecommendationView's `severity` literal-union override must flow through. */
  recommendations: RecommendationView[];
};

export type ReportDocument = Omit<components['schemas']['ReportDocument'], 'teams'> & {
  /** Cascaded override — ReportTeamSection's `recommendations` override must flow through. */
  teams: ReportTeamSection[];
};

export type ReportDocumentView = Omit<
  components['schemas']['ReportDocumentView'],
  'report' | 'document'
> & {
  /** Cascaded override — ReportView's `completedAt` nullability override must flow through. */
  report: ReportView;
  /** Cascaded override — ReportDocument's `teams` override (→ ReportTeamSection) must flow through. */
  document: ReportDocument;
};

// ── M6-B optional AI explanation layer (frontend) ──────────────────────────────────────────────
// AI is optional, per-tenant, OFF by default. It only ever EXPLAINS deterministic numbers already
// computed elsewhere (trends, recommendations, reports) — it is never a new metric source and
// never surfaces individual-level detail (NFR-071). Every AI output carries the API's own
// `disclaimer` string, rendered verbatim, never paraphrased.

/**
 * `provider` is a closed Java enum but springdoc emits it as plain `string` — narrowed back to the
 * literal union here; it is also `@Nullable` under Jackson's default ALWAYS inclusion.
 */
export type AiPolicyView = Omit<
  components['schemas']['AiPolicyView'],
  'provider' | 'baseUrl' | 'model'
> & {
  provider: 'ollama' | 'openai-compatible' | null;
  baseUrl: string | null;
  model: string | null;
};

/** GET /api/v1/ai/status — any dashboard viewer (not admin-only), unlike AiPolicyView.
 *  No `AiStatusView` component exists in the contract — springdoc names this schema `AiStatusResponse`. */
export type AiStatusView = components['schemas']['AiStatusResponse'];

export type ExplanationView = components['schemas']['ExplanationView'];
