@startuml
set separator none
title Events

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("Modules.Modules_boundary", "Modules", $tags="") {
  Component(Modules.Modules.Domain, "Domain", $techn="Module", $descr="", $tags="", $link="")
  Component(Modules.Modules.Events, "Events", $techn="Module", $descr="", $tags="", $link="")
}

Rel(Modules.Modules.Events, Modules.Modules.Domain, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml