/**
 * The `/api/v1` REST surface (BackendPlan §2.4: controllers live only in {@code eip-app}). The
 * first visible slice — {@code session} and {@code connectors} — reads the RLS-protected control
 * plane deterministically; errors are RFC 7807 problem+json. The OpenAPI 3 contract is generated by
 * springdoc at {@code /v3/api-docs}.
 *
 * <p>Null-marked (JSpecify): every reference is non-null unless annotated {@code @Nullable}.
 */
@NullMarked
package com.eip.app.api;

import org.jspecify.annotations.NullMarked;
